---
locale: es
tags: []
layout: input_bottom
editor: 0
type: reading
extra_visible: false
language: ruby
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Nuevo ejercicio
